Fix GPU memory consumption with retina tiles and browser zoom
Leaflet/Leaflet pull request #4959
Opened 2016-09-27 22:17 UTC by davojta

1) switch off will-change
2) add no3d option for layer options
3) add test page

Discussed in https://github.com/Leaflet/Leaflet/issues/4578

2016-09-28 09:27 UTC, mourner commented
There's a reason the was `will-change` in CSS — as far as I remember, `flyTo` animations were excruciatingly slow without it on certain browsers/devices, so removing it will inevitably regress performance in some cases. We may revisit this now but test very thoroughly on iOS, Android, all desktop browsers etc.

2016-09-28 10:33 UTC, davojta commented
@mourner I think we can do it with special flag or just mention it in docs 
They main benefit is option to switch off translate3d for retina tiles and fallback to translate implementation without flooding GPU memory. There is a rare edge case anyway (browser zoom + retina tiles but cause browser crash )

2017-02-21 08:58 UTC, kaynz commented
Any news on this,  @mourner ? :)

2022-01-21 11:44 UTC, Falke-Design requested changes

2022-01-21 11:44 UTC, Falke-Design commented on src/dom/DomUtil.js
>  	// Resets the 3D CSS transform of `el` so it is translated by `offset` pixels
Docs: parameter `no3d` missing

2022-01-21 11:44 UTC, Falke-Design commented on src/dom/DomUtil.js
>  	// Sets the position of `el` to coordinates specified by `position`,
Docs: parameter `no3d` missing

2022-01-21 12:35 UTC, jonkoops commented
A part of this has already landed in #7872. Are the changes of this PR still relevant?

2022-03-14 10:20 UTC, closed without merging