Add Editorconfig
Leaflet/Leaflet pull request #6125
Opened 2018-04-06 18:41 UTC by denysdovhan

See: http://editorconfig.org/

2018-04-07 10:56 UTC, denysdovhan commented
Would you prefer to use this set of settings?

```
# http://editorconfig.org
root = true

[*]
indent_style = tab
indent_size = 4
end_of_line = crlf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

2021-11-14 21:08 UTC, Falke-Design commented
Because there was no request for this since 2018 anymore, I suggest to close this

2022-04-24 22:47 UTC, Malvoz commented on .editorconfig
> +# http://EditorConfig.org
```suggestion
# https://EditorConfig.org
```

2022-04-24 22:49 UTC, Malvoz commented on .editorconfig
> +indent_size = 2
What's the basis for these settings? They'd have to be kept in sync with the ESLint config right? (https://github.com/Leaflet/Leaflet/issues/8176 / https://github.com/Leaflet/Leaflet/issues/3870)

2022-04-24 22:53 UTC, jonkoops requested changes
I don't see the value of adding a config that can become out of sync with our existing linting tools (which are checked by CI). Checking this config is also in no way enforced by any tooling on CI at the moment.

2022-04-24 22:59 UTC, Malvoz commented
Closing per https://github.com/Leaflet/Leaflet/pull/6125#pullrequestreview-951256183, https://github.com/Leaflet/Leaflet/pull/6125#issuecomment-968363321 and https://github.com/Leaflet/Leaflet/pull/2347#issuecomment-32362778.

2022-04-24 22:59 UTC, closed without merging