Add Leaflet-search and Yii2-locator
Leaflet/Leaflet pull request #6971
Opened 2020-01-16 12:56 UTC by sjaakp

2021-11-04 10:22 UTC, johnd0e requested changes

2021-11-04 10:22 UTC, johnd0e commented on docs/plugins.md
> +  <tr>
Use tabs for indentation

2021-11-23 11:59 UTC, Falke-Design commented
@sjaakp please change the PR and resolve the conflicts

2021-11-25 15:01 UTC, Falke-Design commented
We added the plugin in the refactoring where we moved the plugins into seperate files #7805

2021-11-25 15:01 UTC, closed without merging