Plugins.md - Leaflet.Control.Select added to the list of plugins
Leaflet/Leaflet pull request #7050
Opened 2020-03-26 18:45 UTC by adammertel

https://github.com/adammertel/Leaflet.Control.Select

2021-11-04 07:40 UTC, johnd0e commented
@adammertel 
Please resolve conflicts

2021-11-04 10:02 UTC, johnd0e requested changes

2021-11-04 10:02 UTC, johnd0e commented on docs/plugins.md
> +    <td>
Please restore tabs

2021-11-04 10:02 UTC, johnd0e commented on docs/plugins.md
> +  <tr>
tabs

2021-11-04 10:02 UTC, johnd0e commented on docs/plugins.md
> +			 Customisable menu-style control, allows menu-items grouping or multiple-selection mode. See <a href="https://adammertel.github.io/Leaflet.Control.Select/">demo</a>.
Excessive space

2021-11-04 10:02 UTC, johnd0e commented on docs/plugins.md
> +  </tr>
tabs

2021-11-04 14:05 UTC, jonkoops reviewed
Can we get rid of the unrelated white-space changes?

2021-11-04 14:27 UTC, johnd0e requested changes

2021-11-04 14:27 UTC, johnd0e commented on docs/plugins.md
> +    	<td>
Tabs

2021-11-04 14:27 UTC, johnd0e commented on docs/plugins.md
> +  	<tr>
Tabs

2021-11-04 14:27 UTC, johnd0e commented on docs/plugins.md
> +  	</tr>
Tabs

2021-11-04 19:42 UTC, adammertel commented
Sorry guys, it takes so long. Hope it is good now.

2021-11-05 07:19 UTC, mourner approved these changes

2021-11-05 07:19 UTC, merged