Added plugin Leaflet.AnimatedSearchBox to plugins.md
Leaflet/Leaflet pull request #7053
Opened 2020-03-27 21:51 UTC by luka1199

I added my plugin Leaflet.AnimatedSearchBox to the plugins.md.
It provides a collapsible search box.

2020-07-07 10:45 UTC, luka1199 commented
Is there anything I can improve?

2021-11-04 10:17 UTC, johnd0e requested changes

2021-11-04 10:17 UTC, johnd0e commented on docs/plugins.md
> +    </tr>
Please use tabs for indentation

2021-11-06 11:24 UTC, johnd0e approved these changes

2021-11-06 11:24 UTC, merged