DomEvent: keep original event types for transformed events
Leaflet/Leaflet pull request #7064
Opened 2020-04-02 12:42 UTC by johnd0e

Currently for compatibility purposes Leaflet substitute 'touch*' listeners with 'pointer*' ones (where available).
And similarly with 'mouseenter' / 'mouseleave'.

It's not good, as handler may rely on original `type` in own code, so better to keep it.

In proposed modification I pass 'original' type as 2nd argument of handler, and this is enough for events dispatched with `map._fireDOMEvent`: handler then has access both to 'original' event type, and to real type (`originalEvent.type`).

But for listeners attached directly with `DomEvent.on(...` it is not so simple, as `type` property is read-only (as a rule). I believe that we should keep things simple: `type` as second argument is smart enough.
Perhaps, that should be documented.

2020-04-03 07:03 UTC, johnd0e commented
> In proposed modification I pass 'original' type as 2nd argument of handler[...]

Alternatively original value could be passed as event's property `_originalType`.

2020-04-09 21:45 UTC, johnd0e commented
Todo: make use in `Draggable.js`

2021-12-07 17:41 UTC, Falke-Design requested changes
Passing the new type to `_handleDOMEvent` is missing in Canvas:
https://github.com/Leaflet/Leaflet/blob/e3719a317ab325ed091fbbc6bfd34640fe19e13e/src/layer/vector/Canvas.js#L72-L73

For me is the name `originalType` not fitting, because it let me think that is the type of the `pointer` event and not the new `fake` type

2021-12-08 08:34 UTC, johnd0e commented
> Passing the new type to `_handleDOMEvent` is missing in Canvas:

Why do we need it there?

2021-12-08 09:06 UTC, Falke-Design commented
This was very bad described from me sorry ...

You have changed the function arguments of ` _handleDOMEvent` so that the `originalType` is used for `this._fireDOMEvent(e, type);`:
```
_handleDOMEvent: function (e, originalType) {
	// ...
	var type = originalType || e.type;
	// ...
	this._fireDOMEvent(e, type);
```

If Canvas is enabled `_fireDOMEvent` will be called too and then it should also use the `originalType`. Else `pointerevents` will **not** converted to `touchevents`. If SVG is used, it will be converted -> should be the same behaviour for both

------------

Besides from above, the `_handleDOMEvent` is not listening on `touchevents`, so there is currently no need to pass the originalType there, because it will be never fired by a `pointerevent`.
`_handleDOMEvent` is listening only on the following events:
https://github.com/Leaflet/Leaflet/blob/e3719a317ab325ed091fbbc6bfd34640fe19e13e/src/map/Map.js#L1314-L1315

**But** I currently working on the PR to adding touchevents and there I will need the `originalType` in the `_handleDOMEvent`, but a future PR should not be a reason to keep it in this PR

2025-05-06 19:11 UTC, closed without merging