Update plugins.md
Leaflet/Leaflet pull request #7112
Opened 2020-04-25 16:27 UTC by liubingreat

2020-04-25 16:36 UTC, liubingreat commented
add a leaflet plugin, display markers on canvas.

2021-11-04 07:55 UTC, johnd0e requested changes

2021-11-04 07:55 UTC, johnd0e commented on docs/plugins.md
> +			(<a href="http://180.76.171.45:8080/leaflet-canvas-marker/example/label-demo.html">label-demo</a>).
ERR_CONNECTION_TIMED_OUT

2021-11-04 07:56 UTC, johnd0e commented
@liubingreat 
Please resolve conflicts

2021-11-25 15:52 UTC, Falke-Design commented
We changed the design / structur for the plugins site. Now each plugin have a own file. Please reaname your plugin and then create a new PR #7805

2021-11-25 15:52 UTC, closed without merging