Revised for tutorial and example consistency
Leaflet/Leaflet pull request #7269
Opened 2020-09-11 22:55 UTC by flywire

Revised for tutorial and example consistency:

Change tutorial text to address any issues:
- no metadata
- source integrity check causing issues and was removed
- source changed to osm to remove compexities of using registered data
- consolidating `var` statements not described or included in example
- consolidating `.bindPopup` command statements not described or included in example

2020-09-22 20:31 UTC, mourner requested changes
I might address other changes later, but one thing to note is that OSM tile server is not used in the tutorials on purpose — the team behind OSM didn't want us to encourage using it on production websites, since it's not suited to that kind of load and it's expensive to keep. So I can't accept this particular change for sure. E.g. see here https://twitter.com/OSM_Tech/status/1308465290263629825

2020-09-23 00:38 UTC, flywire commented
https://github.com/flywire/Leaflet/commits/patch-1 changed, I expected it would show here.

(Discussed at https://github.com/Leaflet/Leaflet/issues/7254#issuecomment-687609542.)

2020-10-05 04:05 UTC, flywire commented
@mourner requested changes done with #92c8d25

2020-10-05 10:44 UTC, IvanSanchez requested changes

2020-10-05 10:44 UTC, IvanSanchez commented on example-basic.md
> +---
I think you meant to edit files in `docs/`, but the changes here are *adding* files to the root (`/`) directory of the repo instead.

2021-11-26 20:17 UTC, mourner commented
-> #7816

2021-11-26 20:17 UTC, closed without merging