Allow pass custom function in locate to get coordinates
Leaflet/Leaflet pull request #7313
Opened 2020-10-18 10:39 UTC by Nisgrak

Allow to pass a custom function to get coordinates, this allow leaflet to work with Capacitor like this.

The getCoordinates must return a Promise.

```js
this.map.locate({
    getCoordinates: async (options) => {
        return Geolocation.getCurrentPosition(); // Return the same as navigator.geolocation.getCurrentPosition()
    }
})
```

Resolves #7296.

2020-11-11 21:46 UTC, rheh commented on src/map/Map.js
> +					.then(function (pos) {
anonymous function not required,  I think you can just do this:
`options.getCoordinates(options).then(onResponse)`

2020-11-11 21:46 UTC, rheh commented on src/map/Map.js
> +					}).catch(function (error) {
Similair here: I think you can just do this:
`options.getCoordinates(options)
    .then(onResponse)
    .catch(onError)
`

2020-11-11 21:46 UTC, rheh commented on src/map/Map.js
> +						this._locationWatchId = locationWatchId;
Are we sure 'this' Is referring to the context now it is wrapped in an anonymous function.  If the intent is to set _locationWatchId on the map object I think this needs to be an arrow function, or, bind the function to control the context of this?

2020-11-12 19:36 UTC, rheh approved these changes
LGMT

2020-12-10 13:24 UTC, Nisgrak commented
Any changes?

2021-12-01 21:14 UTC, Falke-Design requested changes

2021-12-01 21:14 UTC, Falke-Design commented on src/map/Map.js
> +		if (options.getCoordinates) {
Missing documentation

2021-12-01 21:14 UTC, Falke-Design commented on src/map/Map.js
> +				this._locationWatchId = options.getCoordinates(options, onResponse);
onError is missing

2021-12-02 12:46 UTC, johnd0e commented
> Allow to pass a custom function to get coordinates

It's not about single function. There is `watch` option. There is `stopLocate` method. And all is tied to `navigator.geolocation.*`.

So.. I don't think that we can consistently support custom functions here.
If you need - rewrite `locate` with own method.

2021-12-02 12:46 UTC, closed without merging