Add lineToLayer and polygonToLayer options to GeoJSON layer
Leaflet/Leaflet pull request #7327
Opened 2020-11-02 16:26 UTC by MasterEric

# Summary

This change adds two new options to the GeoJSON layer. These provide similar functionality to the `pointToLayer` function. However, where `pointToLayer` allows an override in behavior in the creation of Markers, `lineToLayer` and `polygonToLayer` override the creation of Polylines/Multipolylines and Polygons/Multipolygons, respectively:

> **lineToLayer**
A Function defining how GeoJSON LineString and MultiLineString geometry types spawn Leaflet layers. It is internally called when data is added, passing the GeoJSON line feature and its LatLngs. The default is to spawn a default Polyline: 
> ```
> function(geoJsonLine, latlngs) {
>     return L.polyline(latlngs);
> }
> ```

> **polygonToLayer**
A Function defining how GeoJSON Polygon and MultiPolygon geometry types spawn Leaflet layers. It is internally called when data is added, passing the GeoJSON polygon feature and its LatLngs. The default is to spawn a default Polygon: 
> ```
> function(geoJsonPolygon, latlngs) {
>     return L.polygon(latlngs);
> }
> ```

# Use Case

This code allows users to use their own objects to define how polylines and polygons are rendered from GeoJSON data onto a Leaflet map.

As an example: If you wanted the GeoJSON line to be rendered as a [L.multiOptionsPolyline](https://github.com/hgoebl/Leaflet.MultiOptionsPolyline) instead of an `L.polyline`, the existing code base did not provide this option to developers.

I encountered this case, and found it odd that only point markers had the option to override in this manner.

# Changes Made

I implemented the relevant code, modified the relevant documentation comments to reflect the new properties, and ensured that code spacing/linting matched that of the surrounding code. I also tested the code functions as intended by adding an example of `lineToLayer` to the documentation, by changing the rendered lines in `docs/examples/geojson` to create polylines with a magenta color.

2020-11-03 07:10 UTC, johnd0e commented
See similar rejected #6539.
And pay attention to failed tests.

2020-11-03 07:40 UTC, MasterEric commented
Attempted resolution of failed test using a squashed commit.

As stated under the Use Case section of the pull request, there are multiple plugins, such as MultiOptionsPolyline and TextPath, which override how lines are created.

I made this pull request in part such that I could use the Github branch as a dependency for my own project, and I am currently utilizing this feature to replace the rendering of a solid line with a TextLine with arrows, to create a directed path.

2020-11-03 07:58 UTC, MasterEric commented
The test suit error is occurring because of the option `markersInheritOptions`; the current code states that by default, the individual lines of the GeoJSON do not inherit the options of the GeoJSON.

The question is how ought the code be revised from here. I see several paths forward:

* Leave the library as is, and the test modified to set `markersInheritOptions` to true. As seen, this is a breaking change so I don't think this is suitable.
* Add new options for `polyLinesInheritOptions` and `polygonsInheritOptions`. Either these have a default value of true (which may be confusing for developers as there are inconsistent default values for similar parameters) or these have a default value of false, which is again a code change which modifies how maps are rendered.
* Remove polylines and polygons for consideration for the `markersInheritOptions` option and have it always inherit. This would result in users maps looking the same, but would leave no ability to allow users to turn inheritance off.

What is the best fix?

2020-12-02 00:33 UTC, MasterEric commented
Apologies for the delay on fixing this PR.

I have opted for the second option, adding the `linesInheritOptions` and `polygonsInheritOptions` parameters, which default to true (as previous version of leaflet inherited options as well).

2020-12-09 11:56 UTC, johnd0e commented on docs/examples/geojson/example.md
> +			console.log('lineToLayer');
```suggestion
```

2020-12-09 11:56 UTC, johnd0e commented on docs/examples/geojson/example.md
> +		}
Something wrong with whitespaces here.

2020-12-09 11:59 UTC, johnd0e commented
> As stated under the Use Case section of the pull request, there are multiple plugins, such as MultiOptionsPolyline and TextPath, which override how lines are created.

Well, I see now that this can be useful.
Still I am not convinced yet that we need to put it into Leaflet core.
How about to make this by plugin extending `L.GeoJSON` with all extra functions?

2021-11-14 19:23 UTC, Falke-Design requested changes
Please update your PR.

I think this features can be useful in Leaflet core, because it makes it a step more easier customizeable which is one of the greate things in Leafet.

2021-11-14 19:23 UTC, Falke-Design commented on src/layer/GeoJSON.js
> +	 * Whether default Markers for "Polyline" type Features inherit from group options.
```suggestion
	 * Whether default Polyline for "LineString" type Features inherit from group options.

```

2021-11-14 19:23 UTC, Falke-Design commented on src/layer/GeoJSON.js
> +	 * Whether default Markers for "Polygon" type Features inherit from group options.
```suggestion
	 * Whether default Polygon for "Polygon" type Features inherit from group options.

```

2021-11-14 19:23 UTC, Falke-Design commented on src/layer/GeoJSON.js
> +	 * passing the GeoJSON line feature and its `LatLngs`.
```suggestion
	 * passing the GeoJSON lineString feature and its `LatLngs`.

```

2021-11-14 19:23 UTC, Falke-Design commented on src/layer/GeoJSON.js
> +	 * 	return L.polyline(latlng);
```suggestion
	 * 	return L.polyline(latlngs);

```

2022-12-31 04:18 UTC, closed without merging