Better example
Leaflet/Leaflet pull request #7386
Opened 2020-12-18 17:51 UTC by stell

https://github.com/Leaflet/Leaflet/issues/6175

2020-12-23 21:51 UTC, rheh requested changes

2020-12-23 21:51 UTC, rheh commented on src/dom/PosAnimation.js
> + * myPositionMarker.on("click", function(){
For consistency add a space between () and {?

2020-12-23 21:51 UTC, rheh commented on src/dom/PosAnimation.js
> + * 	var pos = map.latLngToLayerPoint(myPositionMarker.getLatLng())
No semi-colon on end of line.  Should we add one to be consistant?

2020-12-23 21:51 UTC, rheh commented on src/dom/PosAnimation.js
> + * 	fx.once('end',function(){
Again space between () and {

2020-12-23 21:51 UTC, rheh commented on src/dom/PosAnimation.js
> + *
Remove blank line?

2021-01-03 20:56 UTC, rheh approved these changes

2021-01-04 14:13 UTC, johnd0e commented
@stell @rheh 
Haven't you noticed failed CI-checks?

2021-01-07 15:29 UTC, samuei reviewed
Failed CI messages are from trailing spaces on lines 15, 20, 25, and 28.

2021-01-08 22:01 UTC, rheh commented
> @stell @rheh
> Haven't you noticed failed CI-checks?

TBH I did not, I just reviewed the code.

2022-04-19 06:50 UTC, Falke-Design approved these changes

2022-05-20 14:55 UTC, Falke-Design commented
@Malvoz can you please review

2022-05-20 15:12 UTC, Malvoz approved these changes

2022-05-20 15:16 UTC, merged