Add Leaflet.HighlightableLayers plugin to docs
Leaflet/Leaflet pull request #7437
Opened 2021-01-28 15:40 UTC by cdauth

2021-11-04 09:08 UTC, johnd0e commented
@cdauth 
Please resolve conflicts

2021-11-10 06:29 UTC, Falke-Design requested changes

2021-11-10 06:29 UTC, Falke-Design commented on docs/plugins.md
> +		    Highlight Leaflet lines and polygons by adding a border and raising them above others. Add a transparent border to increase the tolerance for mouse/touch interactions. <a href="https://unpkg.co
Please replace blank with tab
```suggestion
			Highlight Leaflet lines and polygons by adding a border and raising them above others. Add a transparent border to increase the tolerance for mouse/touch interactions. <a href="https://unpkg.com/leaflet-highlightable-layers/example.html">Demo</a>
```

2021-11-10 06:29 UTC, Falke-Design commented on docs/plugins.md
> +		    Add/move/remove points on routes, lines and polygons by drag&drop. <a href="https://unpkg.com/leaflet-draggable-lines/example.html">Demo</a>
Please replace blank with tab
```suggestion
			Add/move/remove points on routes, lines and polygons by drag&drop. <a href="https://unpkg.com/leaflet-draggable-lines/example.html">Demo</a>
```

2021-11-14 04:06 UTC, cdauth commented
@johnd0e @Falke-Design Fixed.

2021-11-14 06:59 UTC, Falke-Design approved these changes
- [x] Tabs used
- [x] All Links are working

@jonkoops kan be merged

2021-11-15 08:58 UTC, johnd0e approved these changes

2021-11-15 08:59 UTC, merged