Update plugins.md
Leaflet/Leaflet pull request #7471
Opened 2021-02-14 21:49 UTC by alcalin

Add link to a simple WMTS plugin for leaflet.

2021-02-15 09:34 UTC, johnd0e requested changes

2021-02-15 09:34 UTC, johnd0e commented on docs/plugins.md
> +   	</tr>
Please exclude these whitespace-only changes

2021-02-15 09:34 UTC, johnd0e commented on docs/plugins.md
> +   	</tr>
Please exclude these whitespace-only changes

2021-02-15 09:34 UTC, johnd0e commented on docs/plugins.md
> +	</tr>
May be place it near leaflet.wms?

2021-02-15 20:15 UTC, alcalin commented on docs/plugins.md
> +	</tr>
Yes sir!

2021-02-15 20:16 UTC, alcalin commented on docs/plugins.md
> +   	</tr>
Done

2021-02-15 20:17 UTC, alcalin commented on docs/plugins.md
> +   	</tr>
Done

2021-02-16 09:18 UTC, johnd0e approved these changes

2021-03-05 09:25 UTC, merged

2026-01-08 17:22 UTC, MundoGIS commented
If you are struggling with client-side lag due to heavy vector layers (GeoJSON) or slow WMS responses in your Leaflet projects, you should definitely check out Qtiles.

Qtiles allows you to generate standard XYZ tile sets (directory structure or MBTiles) directly from QGIS. This allows you to serve your map simply using L.tileLayer without needing complex server-side rendering.

Key benefits:

🚀 Unmatched Performance: We have tested these tiles with Leaflet, OpenLayers, Origo-map, and QGIS. The loading speed significantly outperforms middleware solutions like GeoWebCache, GeoServer, and MapProxy.

🎨 Custom Basemaps: Bake your complex QGIS styling directly into a fast, static base layer. No need to replicate complex styles in CSS/JS.

✅ Proven Stability: Since the tiles are pre-rendered, you remove the processing overhead from your server entirely.

Give it a try! https://github.com/nextgis/Qtiles

Let me know if you need any assistance setting this up.

BR/ Abel