Update Renderer documentation to clarify tolerance option Canvas only
Leaflet/Leaflet pull request #7515
Opened 2021-03-16 21:15 UTC by Hippl-Eric

Fixes #7494 

- Renderer documentation does not clarify the [tolerance ](https://leafletjs.com/reference-1.7.1.html#renderer-tolerance ) option is only supported by Canvas (not SVG) renderer.
- Update documentation to reflect this.
- Refer to similar instance in documentation: Path [className](https://leafletjs.com/reference-1.7.1.html#path-classname) option

2021-03-17 08:55 UTC, johnd0e commented
Our documentation is autogenerated from source comments, so the fix should be in `Renderer.js`.

> * Refer to similar instance in documentation: Path [className](https://leafletjs.com/reference-1.7.1.html#path-classname) option

Not exactly a good example for this case.

I have in mind 2 alternative ways:
1. Note that `tolerance` is defined not in `Canvas.js`. So simplest fix would be just move it there.
2. Or we can consider this as generic renderer option, which is subject to be (or not) implemented in respective renderers.
   This case requires more general wording, saying that the option requires support from renderer, and SVG lacks one.

In fact I'm not sure what way should be chosen.
May be let's start from 1 and wait for other opinions.

2021-03-19 15:38 UTC, Hippl-Eric commented
> Our documentation is autogenerated from source comments, so the fix should be in `Renderer.js`.

I reverted commit to incorrect file `reference-1.7.1.html`.  Awaiting direction before modifying `Renderer.js`.

> In fact I'm not sure what way should be chosen.
> May be let's start from 1 and wait for other opinions.

I can work through implementing 1, but can you please clarify what you are expecting?  As you point out, `tolerance` is not defined in `Canvas.js` - it is defined in `Renderer.js`:
https://github.com/Leaflet/Leaflet/blob/0f904a515879fcd08f69b7f51799ee7f18f23fd8/src/layer/vector/Renderer.js#L39-L41
`Canvas` does not have an `options` property (only inherited).  Are you suggesting to add an `options` property to `Canvas` with one nested property `tolerance : 0`?  Then removing the `tolerance` from `Renderer`?

2021-03-19 17:34 UTC, johnd0e commented
> Canvas does not have an options property (only inherited). Are you suggesting to add an options property to Canvas with one nested property tolerance : 0? Then removing the tolerance from Renderer?

That is exactly what I mean, right.

2021-03-25 13:22 UTC, Hippl-Eric commented
@johnd0e I completed the following changes:

1. Moved tolerance option from `Render` to `Canvas`
2. Updated `Path_clickTolerance` to handle possible renderers that do include a tolerance option (all `SVG` renderers now)

2021-03-25 14:11 UTC, johnd0e requested changes

2021-03-25 14:11 UTC, johnd0e commented on src/layer/vector/Path.js
> +		(this._renderer.options.tolerance ? this._renderer.options.tolerance : 0);
```suggestion
		  (this._renderer.options.tolerance || 0);
```

2021-03-25 14:45 UTC, johnd0e approved these changes

2021-11-26 09:14 UTC, merged