Tooltip events
Leaflet/Leaflet pull request #7532
Opened 2021-03-28 20:17 UTC by johnd0e

`mytooltip.on('click', ...`

(based on #3571)

2021-11-01 11:10 UTC, Falke-Design requested changes
Because of https://github.com/Leaflet/Leaflet/pull/7531#issuecomment-955696600:
The events on the tooltip is not working because of:
https://github.com/Leaflet/Leaflet/blob/f018e2de2ce507ab9b070f382e6bded9b9311263/src/layer/Tooltip.js#L71-L76

it adds the interactiveTarget to the `source` and not to the layer self. This is fixed with this PR additionally it adds the event parent `source` which makes the changes not to a breaking change.

I came after my research to the exact same changes

2021-11-01 11:10 UTC, Falke-Design commented on src/layer/Tooltip.js
> +			DomUtil.addClass(this._container, 'leaflet-clickable');
New class `leaflet-interactive` should be used

2021-11-01 11:10 UTC, Falke-Design commented on src/layer/Tooltip.js
> +			DomUtil.removeClass(this._container, 'leaflet-clickable');
New class `leaflet-interactive` should be used

2021-11-01 11:21 UTC, Falke-Design commented
And maybe `this._source.fire('tooltipclose', {tooltip: this}, true);` should be then fired on the tooltip self and with the event parent it is also fired on the source layer

2021-11-01 11:41 UTC, Falke-Design requested changes

2021-11-01 11:41 UTC, Falke-Design commented on src/layer/Tooltip.js
>  			DomUtil.addClass(this._container, 'leaflet-interactive');
`leaflet-clickable` is still added

2021-11-01 12:15 UTC, Falke-Design approved these changes
Looks good! Next step to mark PR "ready for review"

2021-11-01 16:44 UTC, johnd0e commented
> And maybe `this._source.fire('tooltipclose', {tooltip: this}, true);` should be then fired on the tooltip self and with the event parent it is also fired on the source layer

Please explain what you mean

2021-11-01 16:48 UTC, Falke-Design commented
With `this._source.fire('tooltipclose', {tooltip: this}, true);` the event `tooltipclose` is only fired on the source layer, but it would make sense to fire this on the tooltip too. So it should changed to `this.fire('tooltipclose', {tooltip: this}, true);`

2021-11-01 16:52 UTC, johnd0e commented
> So it should changed to `this.fire`

No, should fire on source layer - it is really intended so.

2021-11-01 16:54 UTC, johnd0e commented
> Next step to mark PR "ready for review"

Next step is decide how to be with closing on `preclick`.

P.S.
And final step - describe possible use cases. Do you have some?

2021-11-01 17:02 UTC, Falke-Design commented
> No, it should fire on source layer - it is really intended so.

But why? A tooltip can also be a own layer on the map, so why not fireing events on it?

```
		var tooltip = L.tooltip().setContent('Tooltip');
		map.openTooltip(tooltip, map.getCenter());
		
		tooltip.on('tooltipclose',(e)=>console.log('Tooltip',e));
		map.on('tooltipclose',(e)=>console.log('Map',e));
```

2021-11-01 17:32 UTC, johnd0e commented
> But why? A tooltip can also be a own layer on the map, [...]

So it already has all related events ('remove', not 'tooltipclose')

2021-11-01 18:02 UTC, Falke-Design commented
> So it already has all related events ('remove', not 'tooltipclose')

Ok yes sorry, you are right didn't thought about that one.

> Next step is decide how to be with closing on preclick.

Ah sorry, didn't thought that you want to add this in this PR.
I don't think that new function instead of  `preclick` will be good, because it breaks current behaviour. It doesn't close anymore on click on the map or on the tooltip. It closes only if a new tooltip is open or `closeTooltip()` is called.

> And final step - describe possible use cases. Do you have some?

I know that had some usecase where I wanted to add a click listener on the tooltip. But I don't know for what exactly anymore. 
Other usecases would be to make Tooltips dragable, specially if they are added as a own layer without "source". Or to make a "Click me to revert" Tooltip after removing a layer, ...

2021-11-02 09:13 UTC, johnd0e commented
> It doesn't close anymore on click on the map or on the tooltip.

It will be easy to add too, but with clear map `click`.

> Ah sorry, didn't thought that you want to add this in this PR.

But you are right, it is not necessary in this PR.

> I know that I had some usecase

Me too)

2021-11-02 09:17 UTC, Falke-Design approved these changes

2021-11-02 09:44 UTC, mourner approved these changes
Nice! How do we surface this in the docs?

2021-11-02 09:50 UTC, Falke-Design commented
Good point.

This section is missing:
![image](https://user-images.githubusercontent.com/19800037/139824363-3c155fee-fc1c-4019-9beb-d656587f465e.png)

2021-11-02 10:45 UTC, johnd0e commented
May be this way: 9251b807f70ca68c41217df8201ac7938b6c9743

2021-11-02 10:56 UTC, Falke-Design commented
But then DivOverlay and Popup would be "marked" as interactive too, but the code is missing. `popup.on('click',(e)=>console.log(e))` is not working.
```
var layer = new L.Marker(map.getCenter()).bindPopup('TEST').addTo(map);
layer.getPopup().on('click',(e)=>console.log(e))
```
https://jsfiddle.net/falkedesign/xqc9mbzd/

2021-11-02 14:24 UTC, johnd0e commented
Perhaps not every descendant of `DivOverlay` must to be `interactive`.
But I do not know if **LeafDoc** has ability to attach `Interactive layer` class 'in the middle', so..

@mourner @IvanSanchez 
Ideas?

2021-11-02 17:19 UTC, johnd0e commented
@Falke-Design 
Something like this?

2021-11-03 17:31 UTC, Falke-Design approved these changes
Nice!

Good to know: `click` event will not fire on the Popup because of:
https://github.com/Leaflet/Leaflet/blob/cc9f327b41d5a283af40beae195d196ca4089599/src/layer/Popup.js#L184

2021-11-07 16:57 UTC, johnd0e commented
> Good to know: `click` event will not fire on the Popup

Because of #7750.

2021-12-17 17:16 UTC, Falke-Design commented
@johnd0e can you please resolve the conflicts and mark the PR as ready for review. I would say we keep this PR in the 1.8.0 milestone, because it was already approved by @mourner and then it is a small task to check the changes since them and then merge it.

2022-02-07 08:45 UTC, Falke-Design approved these changes
@mourner valid for me, the tests are covering all changes

2022-02-07 08:51 UTC, merged