Fix exception Invalid LatLng object: (NaN, NaN) with the firefox debu…
Leaflet/Leaflet pull request #7567
Opened 2021-05-07 09:28 UTC by SuperPat45

…gger in the mobile simluator mode

Fix a problem with the Firefox debugger in simulated mobile mode who pointerdown event received have two touches with the same coordinate which leaflet does not handle correctly.

Fix bug #7566

2021-11-08 16:46 UTC, jonkoops requested changes
Can you add a test for this behavior?

2022-01-19 10:39 UTC, closed without merging

2022-01-19 10:57 UTC, Falke-Design commented
@mourner have you closed this? Or is this automatically happened with deleting the master branch? There are many other PRs too

2022-01-19 11:03 UTC, Falke-Design commented
PRs which are auto-closed:
- #7567 
- #3955 
- #6066 
- #6248 
- #7364 
- #6676 
- #6935

maybe more?

2022-01-19 11:10 UTC, mourner commented
> Or is this automatically happened with deleting the master branch? There are many other PRs too

Yeah, it appears this happened automatically, I didn't anticipate this. Let's open an issue and track closed PRs we're still interested in.