added `leaflet hex timeslider` plugin
Leaflet/Leaflet pull request #7590
Opened 2021-06-01 09:07 UTC by albertkun

Would like to contribute my plugin to the Leaflet library.

![image](https://user-images.githubusercontent.com/8574425/120297634-25c0eb00-c27e-11eb-8ff6-85fdfd8c5d50.png)

2021-06-01 09:47 UTC, johnd0e commented
@albertkun Have you closed this intentionally?

2021-06-01 11:02 UTC, albertkun commented
@johnd0e yeah, as while it is functional, I think I could do a better job of documenting for general use. If you think its worth adding, though, I would be happy to re-open this PR.

2021-06-01 11:27 UTC, johnd0e commented
I've reopened it as Draft.
Please tell us when it is ready

2021-06-01 11:37 UTC, albertkun commented
@johnd0e will do! thank you!

2021-11-23 11:57 UTC, Falke-Design requested changes
Please change the PR and mark it as "ready for review"

2021-11-23 11:57 UTC, Falke-Design commented on docs/plugins.md
> +			<a href="https://github.com/zimmicz/Leaflet-Timeline-Control">Leaflet Hex Time Slider</a>
```suggestion
			<a href="https://github.com/albertkun/leaflet_hex_timeslider/">Leaflet Hex Time Slider</a>
```

2021-11-23 11:57 UTC, Falke-Design commented on docs/plugins.md
> +			<a href="https://github.com/albertkun/leaflet_hex_timeslider/">Albert Kochaphum</a>
```suggestion
			<a href="https://github.com/albertkun/">Albert Kochaphum</a>
```

2021-11-25 15:00 UTC, Falke-Design commented
We added the plugin in the refactoring where we moved the plugins into seperate files #7805

2021-11-25 15:00 UTC, closed without merging