Update plugins.md
Leaflet/Leaflet pull request #7598
Opened 2021-06-16 09:48 UTC by Aldo-f

Fixing couple of 404

2021-06-22 12:55 UTC, johnd0e requested changes

2021-06-22 12:55 UTC, johnd0e commented on docs/plugins.md
> +			<a href="https://github.com/brunob/leaflet.fullscreen">leaflet.fullscreen</a>
```suggestion
			<a href="https://brunob.github.io/leaflet.fullscreen/">leaflet.fullscreen</a>
```

2021-06-22 12:55 UTC, johnd0e commented on docs/plugins.md
> +			<a href="https://github.com/elidupuis/leaflet.zoomfs">leaflet.zoomfs</a>
```suggestion
			<a href="https://elidupuis.github.io/leaflet.zoomfs/">leaflet.zoomfs</a>
```

2021-06-22 20:13 UTC, Aldo-f commented
Wouldn't it be better to just link to the GitHub?

I think, for keeping it safe/consistent, that would be the better option.

Or is the ultimate goal to link all resources to an individual github.io page (if it exists)?

2021-11-04 07:52 UTC, johnd0e commented
@Aldo-f 
Please resolve conflicts

2021-11-06 15:25 UTC, Aldo-f commented
It seems the 404's are already fixed on master.
No need to fix these conflicts.

2021-11-06 15:25 UTC, closed without merging