Bug Fix for issue 7627
Leaflet/Leaflet pull request #7637
Opened 2021-08-18 06:39 UTC by steff1986

Root cause is issue in argument 'levelsDeep' if unbalanced arrays are inputted. Then, the input argument may not represent the actual dimension of the input array. A check for flatness corrects the issue though there might be better solutions.

2021-08-18 09:59 UTC, mourner requested changes
Can you please provide a test case that demonstrates why the change is needed?

2021-08-18 09:59 UTC, mourner commented on src/layer/GeoJSON.js
> +// Check for flat arrays required to ensure unbalanced arrays are correctly converted in recursion
Nit: I'd move the comment inside so that it's not exposed as public documentation.

2021-08-31 15:09 UTC, Falke-Design commented
Linking issue:
Fix: #7627

2021-11-11 14:17 UTC, johnd0e requested changes
Please resolve conflicts

2022-08-28 20:33 UTC, mourner approved these changes

2022-08-28 20:33 UTC, merged