New Plugin: Locations & Areas
Leaflet/Leaflet pull request #7640
Opened 2021-08-23 20:55 UTC by 100wunder

2021-11-01 11:51 UTC, jonkoops approved these changes
Looks good but there are some conflicts that will need to be resolved.

2021-11-01 12:14 UTC, 100wunder commented
@jonkoops I fixed the merge conflict. Thanks for your support!

2021-11-01 22:25 UTC, Falke-Design approved these changes

2021-11-10 06:17 UTC, Falke-Design requested changes

2021-11-10 06:17 UTC, Falke-Design commented on docs/plugins.md
> +    <td>
Please replace all blanks with tabs
```suggestion
	<td>
```

2021-11-10 16:42 UTC, johnd0e requested changes

2021-11-10 16:42 UTC, johnd0e commented on docs/plugins.md
> +  <tr>
Tabs

2021-11-10 16:42 UTC, johnd0e commented on docs/plugins.md
> +    <td>
Tabs

2021-11-10 17:19 UTC, Falke-Design requested changes

2021-11-10 17:19 UTC, Falke-Design commented on docs/plugins.md
> +		</td><td>
Please move `<td>` to a new line

2021-11-10 17:19 UTC, Falke-Design commented on docs/plugins.md
> +		</td><td>
Please move `<td>` to a new line

2021-11-10 17:19 UTC, Falke-Design commented on docs/plugins.md
> +  	<tr>
Use tabs

2021-11-10 17:19 UTC, Falke-Design commented on docs/plugins.md
> +  	</tr>
Use tabs

2021-11-10 17:19 UTC, Falke-Design commented on docs/plugins.md
> +    	</td>
Use tabs

2021-11-10 17:19 UTC, Falke-Design commented on docs/plugins.md
> +    		</ul>
Use tabs

2021-11-11 08:45 UTC, 100wunder reviewed
@Falke-Design Thanks for your suggestions! I added consistency with tabs and table structure before already and currently wait for @johnd0e approval. It's always possible to optimize further but IMO this should be topic of a future PR.

2021-11-23 12:05 UTC, Falke-Design commented
@100wunder you need to change your PR. You can replace the blanks with tabs or you remove the changes that are not necessary for you.

2021-11-23 13:45 UTC, 100wunder commented
@Falke-Design okay I did

2021-11-23 16:34 UTC, 100wunder commented
@johnd0e If you find some time would you please review? I had send you a review request.

2021-11-25 14:59 UTC, Falke-Design commented
We added the plugin in the refactoring where we moved the plugins into seperate files #7805

2021-11-25 14:59 UTC, closed without merging

2021-11-26 17:03 UTC, 100wunder commented
Thanks @Falke-Design, @jonkoops and @johnd0e for your contributions and support.