Added nautical scale
Leaflet/Leaflet pull request #7788
Opened 2021-11-18 12:49 UTC by christiangrs

Added nautical scale with nautical miles and yards.

2021-11-18 13:02 UTC, Falke-Design requested changes
Please revert the changes in the `reference.html` it is generated automatically.

Would look like that:
![image](https://user-images.githubusercontent.com/19800037/142420333-b8076f86-a848-4d21-871f-1a94439ab814.png)

Running sample: https://plnkr.co/edit/ODFqo4Gs6coMfovr

2021-11-18 13:02 UTC, Falke-Design commented on src/control/Control.Scale.js
> +			this._iScale = DomUtil.create('div', className, container);
Change `_iScale` to `_nScale`

2021-11-18 13:02 UTC, Falke-Design commented on src/control/Control.Scale.js
> +			this._updateScale(this._iScale, yards + ' yd', yards / maxYards);
Change `_iScale` to `_nScale`

2021-11-18 13:02 UTC, Falke-Design commented on src/control/Control.Scale.js
> +			this._updateScale(this._iScale, miles + ' nmi', miles / maxMiles);
Change `_iScale` to `_nScale`

2021-11-18 13:19 UTC, Falke-Design approved these changes
Checked with google converter meter to yard, yard to nauticalmiles. It uses the same faktors for converting.

2021-11-18 15:31 UTC, jonkoops commented
Is this a functionality we'd want to include in the core? This seems like it could quite easily be a plugin. @mourner WDYT?

2021-11-19 23:02 UTC, christiangrs reviewed
Reviewed

2022-09-26 11:30 UTC, Falke-Design commented
> Is this a functionality we'd want to include in the core? This seems like it could quite easily be a plugin. @mourner WDYT?

@mourner? Closing or merging?

2022-12-21 18:15 UTC, jonkoops commented
I'm closing this PR as I don't believe this functionality needs to be in the core of Leaflet. Feel free to create a plugin that allows users to use this functionality if it is useful to them.

2022-12-21 18:15 UTC, closed without merging