Accessibility popup close button
Leaflet/Leaflet pull request #7794
Opened 2021-11-21 08:41 UTC by Falke-Design

- Change the color of the close button for a better contrast #7539 
- Add `role=button` and the `aria-label='Close popup'` to the `<a>` element #7399
- Add `aria-hidden` to the `times` / `x` character to prevent the reading of screen readers #7472

Close Button old:
![grafik](https://user-images.githubusercontent.com/19800037/142755448-75e28123-ab65-4ff1-89d3-d2a1470aee4f.png)
New:
![grafik](https://user-images.githubusercontent.com/19800037/142755418-a01e9e42-7729-4de4-8c80-cf9b6e60b663.png)

Fix: #7539, #7399, #7472

@Malvoz fyi

2021-11-21 08:55 UTC, Malvoz approved these changes
Nice, LGTM!

2021-11-25 17:39 UTC, mourner requested changes
This looks great! I find the close button too jarring when simpling making the color darker, but not if we remove the bold font:

![image](https://user-images.githubusercontent.com/25395/143483825-8cf29f60-3ec4-4f3e-95f0-2f60d2dc86ac.png)

2021-11-25 17:39 UTC, mourner commented on dist/leaflet.css
>  	font-weight: bold;
```suggestion
```

2021-11-25 17:46 UTC, mourner approved these changes

2021-11-25 17:50 UTC, merged

2021-11-28 11:17 UTC, ahukkanen commented
The close button is still not accessible for other languages than English because the label cannot be translated.

2021-11-28 13:38 UTC, Malvoz commented
@ahukkanen https://github.com/Leaflet/Leaflet/issues/3210#issuecomment-634066856:

> Regarding translations: [internationalization isn't built into leaflet core](https://github.com/Leaflet/Leaflet/pull/1232) but it is available as a plugin - https://github.com/yohanboniface/Leaflet.i18n

I suppose you could open a separate issue, or ask if the maintainers could reconsider https://github.com/Leaflet/Leaflet/pull/1232, but that's off topic from this PR?

2021-12-09 15:21 UTC, ahukkanen commented
@Malvoz Thanks for the context!

After reading that i18n discussion, I'm not too certain I could convince the maintainers otherwise than what was discussed there.

At https://github.com/Leaflet/Leaflet/pull/7079#issuecomment-634080439 I tried to suggest to make the hard coded texts configuration options instead of hard coded. This way it would be possible to change programmatically without the need of creating a separate i18n layer in the core.