Replace Mapbox with OpenStreetMap
Leaflet/Leaflet pull request #7818
Opened 2021-11-26 19:25 UTC by Falke-Design

Because of https://github.com/Leaflet/Leaflet/issues/6336#issuecomment-954095682 I suggest to use OpenStreetMap tiles.

> You need permission for heavy use - is this heavy use? Who knows because that term is completely undefined which is why everybody that asks OWG just gets a shrug in response. That part of the policy is just stupid but nobody knows what else to say.

_Originally posted by @tomhughes in https://github.com/Leaflet/Leaflet/issues/6336#issuecomment-954095682_

Fix: #6336

2021-11-26 20:19 UTC, mourner requested changes
Tabs again please :( I'll some lint rules afterwards to check this.

2021-11-26 20:44 UTC, Falke-Design commented
Fixed! Thank you for seeing this. I don't know why my IDE has the option "spaces to tabs" if it is not working ...

2021-11-27 07:56 UTC, johnd0e commented
I like Mapbox tiles

2022-04-18 12:19 UTC, Malvoz commented
> I like Mapbox tiles

With MapBox tiles the issue as described in https://github.com/Leaflet/Leaflet/issues/6336 remains:

> apparently the mapbox tokens are confusing more people.

2022-04-19 15:12 UTC, IvanSanchez submitted a review, later dismissed
Unfortunately this conflicts with the whole "let's move the website to a `/SlavaUkraini` path" thing from #8025. There's some renaming to do.

2022-04-19 15:12 UTC, IvanSanchez commented on docs/examples/quick-start/index.md
> +Next, we'll add a tile layer to add to our map, in this case it's a OpenStreetMap tile layer. Creating a tile layer usually involves setting the [URL template](/reference.html#tilelayer-url-template)
I would like to see some kind of link to https://operations.osmfoundation.org/policies/tiles/ here, along the lines of "OSM tiles are fine for programming your Leaflet map, but read this if you're going to make heavy use of the tiles"

2022-05-19 12:58 UTC, Malvoz approved these changes
LGTM, there will be discrepancies between thumbnails for tutorials and actual tiles used but I think that's fine.

2022-05-27 08:32 UTC, mourner approved these changes

2022-05-27 08:33 UTC, merged