Improve site accesibility
Leaflet/Leaflet pull request #7901
Opened 2022-01-10 23:48 UTC by MxDui

Tasks completed as described in #7899 and I also formatted the  docs/docs/css/main.css file with prettier

2022-01-10 23:57 UTC, Malvoz approved these changes
I haven't tested it, but reviewed the HTML, looks good!

2022-01-11 00:04 UTC, Malvoz commented
@MxDui Just a tip, if you use a [keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) before the issue number (for example "fix #7899" it will automatically close after the maintainers merge the PR.

2022-01-11 00:06 UTC, MxDui commented
@Malvoz Thank you for the feedback!

2022-01-11 06:25 UTC, Falke-Design commented
@MxDui thanks for your contribution.
In Leaflet we use `tabs` as seperator and not `blanks / spaces`, so your prettified css-file is different to the other css-files (and a few other things also styled different). I don't know if this is ok here, this needs to be decided by @mourner

2022-01-11 07:36 UTC, mourner requested changes
Yes, please revert the whitespace formatting in the CSS file.

2022-01-11 14:14 UTC, Malvoz commented on docs/docs/css/main.css
> +p.taglijne {
There's a spelling error "taglijne" here, should be "tagline".

2022-01-12 18:58 UTC, Malvoz approved these changes

2022-01-13 10:58 UTC, mourner approved these changes

2022-01-13 16:59 UTC, merged