Add `playsInline` attribute on the video element
Leaflet/Leaflet pull request #7928
Opened 2022-01-19 12:23 UTC by Falke-Design

The main PR was closed because we renamed the `master` branch to `main`. 
For more infos look into: #7357

Fixes #7357

2022-01-20 08:28 UTC, Malvoz commented
re https://github.com/Leaflet/Leaflet/pull/7364#issuecomment-738780363:

> I'd rather not merge until it has been tested (and I don't have a iOS device either)

I think this should be good to merge. `playsinline` would simply allow videos to play without automatically going into fullscreen mode, in browsers where they otherwise would.

Without `playsinline`:
https://css-tricks.com/what-does-playsinline-mean-in-web-video/#:~:text=what%20it%20looks%20like%20without%20playsinline

With `playsinline`:
https://css-tricks.com/what-does-playsinline-mean-in-web-video/#:~:text=what%20it%20looks%20like%20with%20playsinline

2022-01-20 08:28 UTC, Malvoz approved these changes

2022-01-20 09:10 UTC, Falke-Design commented
We should setup a demo, so that we can easy share a link to check if it works. 
We can set it up in leafletjs.com/edit.html and then I can upload it to my server, because on phones the plunk doesn't work.

2022-01-20 10:52 UTC, jonkoops requested changes

2022-01-20 10:52 UTC, jonkoops commented on src/layer/VideoOverlay.js
> +		vid.playsInline = true;
Let's make this an option like all the other ones, there might be use-cases where someone would actually want to have this play in full-screen.

2022-01-20 19:43 UTC, Falke-Design commented
Here a link to test on a mobile device: http://falke-design.bplaced.net/leaflet/video/videooverlay.html

2022-01-21 12:39 UTC, jonkoops approved these changes
LGTM

2022-01-21 12:46 UTC, jonkoops commented
@Falke-Design could you rebase this on `main`? I'd like to see if Bundlemon reports the file size increase properly.

2022-01-21 12:50 UTC, Falke-Design commented
@jonkoops does it work?

2022-01-21 12:53 UTC, jonkoops commented
Strangely enough it reports a smaller size, which seems impossible. I'll wait for some more PRs so we can see is this is a persistent problem.

2022-01-21 12:53 UTC, merged