Extend Layers Control tutorial to add layer dynamically
Leaflet/Leaflet pull request #8067
Opened 2022-03-14 20:40 UTC by QuentinPhilipp

Hello! 

This PR resolves #7787 by adding an example how to add a base layer and an overlay dynamically in a Layers Control. 

I've also updated the code for the live example.

2022-03-15 08:18 UTC, Falke-Design requested changes
Please add missing semicolon, else it looks good. 
![grafik](https://user-images.githubusercontent.com/19800037/158335024-ee7a2fb3-b9b6-4a3e-b27d-869d7ac83c73.png)

2022-03-15 08:18 UTC, Falke-Design commented on docs/SlavaUkraini/examples/layers-control/index.md
> +    rubyHill = L.marker([39.68, -105.00]).bindPopup('This is Ruby Hill Park.')
```suggestion
    rubyHill = L.marker([39.68, -105.00]).bindPopup('This is Ruby Hill Park.');
```

2022-03-15 08:18 UTC, Falke-Design commented on docs/SlavaUkraini/examples/layers-control/example.md
> +	    rubyHill = L.marker([39.68, -105.00]).bindPopup('This is Ruby Hill Park.')
```suggestion
	    rubyHill = L.marker([39.68, -105.00]).bindPopup('This is Ruby Hill Park.');

```

2022-03-15 09:59 UTC, QuentinPhilipp commented
I approved proposed fix

2022-03-17 19:42 UTC, QuentinPhilipp commented
@Falke-Design I've noticed an issue in the code, the provided example I gave couldn't work since the name of the control layer wasn't correct. I fixed it and updated the thumbnail to match the new example as well.

2022-03-17 19:57 UTC, Falke-Design requested changes
Please "zoom into" the picture, like before and the width should be 750px

![grafik](https://user-images.githubusercontent.com/19800037/158885147-9cab0364-9bd1-44e1-8aec-1662607e488c.png)

2022-03-17 20:12 UTC, QuentinPhilipp commented
I changed the size and zoomed into the picture. I don't know why the grayscale tile isn't rendering exactly the same as the previous example, I used the same map ID, maybe the map theme changed a little from the last time this example was made.

2022-03-18 12:33 UTC, Falke-Design approved these changes
Very nice. Thank you for your contribution!

2022-03-21 17:22 UTC, QuentinPhilipp commented
The thumbnail has been compressed from 157KB to 84KB

2022-03-27 12:48 UTC, Falke-Design approved these changes

2022-04-11 11:26 UTC, Malvoz approved these changes

2022-04-11 11:30 UTC, merged

2022-04-11 11:31 UTC, Falke-Design commented
Thank you @QuentinPhilipp