Issue #7434
Leaflet/Leaflet pull request #8088
Opened 2022-03-26 18:29 UTC by stephenspol

Not sure everything was covered. Feedback is welcomed.

2022-03-26 18:32 UTC, mourner requested changes
This is great, thanks so much for taking on this!

2022-03-26 18:32 UTC, mourner commented on spec/suites/dom/DomEventSpec.js
> +	describe.only('#off (removeListener)', function () {
Looks like a leftover, right? 

```suggestion
	describe('#off (removeListener)', function () {

```

2022-03-26 18:32 UTC, stephenspol commented on spec/suites/dom/DomEventSpec.js
> +	describe.only('#off (removeListener)', function () {
Yep

2022-03-26 19:10 UTC, Falke-Design commented
Does this make #7453 obsolete?

2022-03-26 19:22 UTC, Falke-Design commented
@stephenspol please run `npm run lintfix`

2022-03-27 08:26 UTC, mourner approved these changes
Great! Can you also please check if #7453 is still relevant?

2022-03-27 08:26 UTC, merged

2022-03-27 12:47 UTC, Falke-Design commented
I closed #7453 no need to keep it open.