leaflet-radar
Leaflet/Leaflet pull request #8097
Opened 2022-03-30 09:26 UTC by cygis2011

2022-03-30 09:44 UTC, Falke-Design requested changes

2022-03-30 09:44 UTC, Falke-Design commented on docs/_plugins/overlay-animations/leaflet-radar.md
> +compatible-v0:
```suggestion
compatible-v0: false
```

2022-03-30 09:44 UTC, Falke-Design commented on docs/_plugins/overlay-animations/leaflet-radar.md
> +---
```suggestion
---

Radar sector scan animation
```

2022-03-30 09:45 UTC, Falke-Design approved these changes

2022-03-31 08:48 UTC, Falke-Design commented
We need to wait until another Maintainer approved it

2022-03-31 09:56 UTC, mourner approved these changes

2022-03-31 09:56 UTC, merged