attribution flag now resizes with font-size changes
Leaflet/Leaflet pull request #8183
Opened 2022-04-24 15:46 UTC by sumitsaurabh927

Tested on Chrome on Fedora and things are working fine. I changed font-size in Chrome's console and the attribution flag changed accordingly.

2022-04-24 21:04 UTC, Malvoz commented on src/control/Control.Attribution.js
> +var ukrainianFlag = '<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="12" height="8" + viewBox="0 0 12 8" class="leaflet-attribution-flag"><path fill="#4C7BE1" d="M0 0h12v4H0z"/><pat
Copy paste error? `+` Should not be included here.

2022-04-24 21:05 UTC, Malvoz requested changes
IE treats `height: auto` on the SVG differently from modern browsers such as Chrome and Firefox, resulting in a visual bug. Will need to resolve this.

2022-04-25 08:28 UTC, sumitsaurabh927 commented
I've removed `+` sign in the latest commit. Unfortunately I don't have access to IE. How else can I contribute? When will my PR be merged?

2022-04-25 09:00 UTC, mourner requested changes
Please only add the necessary changes to fix the bug, don't make unrelated changes — the `vertical-align` was there for a reason but was removed, and `!important` is necessary too. Also please keep formatting consistent.

2022-04-25 09:19 UTC, sumitsaurabh927 commented
I'm so sorry. I've fixed my mistakes and added back `vertical-align` and `!important`. I'm presuming the comment was the issue with consistency and have removed it. Shall I push these changes?

2022-04-25 09:25 UTC, Falke-Design commented
Yes always push your changes if you are sure that they are ready to review

2022-04-25 09:28 UTC, sumitsaurabh927 commented
Done. Thanks for the tip!

2022-04-25 11:05 UTC, mourner reviewed
The changes looks good now — let's see if we can find a way to resolve the issue in IE, maybe @Malvoz has ideas?

2022-04-25 11:05 UTC, mourner commented on dist/leaflet.css
> +.leaflet-attribution-flag{
```suggestion
.leaflet-attribution-flag {
```

2022-04-25 12:46 UTC, sumitsaurabh927 commented on dist/leaflet.css
> +	height: auto;
Done and pushed!

2022-04-25 12:54 UTC, Malvoz commented on dist/leaflet.css
> +	height: auto;
The height value in https://github.com/Leaflet/Leaflet/pull/8183/commits/c554d64f8e5ca4414983f68f5872cbbe350ff150 computes to `8.025px` (on normal document font size, on my device). Don't know if this is bothering anyone. The suggested value here would compute to `8px` in the same scenario.

@mourner?

2022-04-25 13:27 UTC, Malvoz commented on dist/leaflet.css
> +	height: auto;
@sumitsaurabh927 Did you mean to change the value from the [suggested](https://github.com/Leaflet/Leaflet/pull/8183#discussion_r857570861) one?

2022-04-25 13:32 UTC, sumitsaurabh927 commented on dist/leaflet.css
> +	height: auto;
I originally set it to auto but you [suggested](https://github.com/Leaflet/Leaflet/pull/8183#discussion_r857570861) it to be `0.669em` so I set it to that. ( I thought it fixed height bug in IE)

2022-04-25 13:33 UTC, Malvoz commented on dist/leaflet.css
> +	height: auto;
I suggested `0.6669em`, but you set it to `0.669em`.

2022-04-25 14:05 UTC, sumitsaurabh927 commented
I'm so sorry for this! Stupid mistake 🤦‍♂️
Rectified it and pushed!

2022-04-27 06:28 UTC, sumitsaurabh927 commented on dist/leaflet.css
> +}
Sorry this escaped my attention, fixed and pushed!

2022-04-27 08:20 UTC, mourner approved these changes

2022-04-27 08:20 UTC, mourner commented
Thank you!

2022-04-27 08:20 UTC, merged

2022-04-27 08:42 UTC, sumitsaurabh927 commented
Thank you! This was my first contribution to an open source and needless to say I'm beyond happy that it has been merged. I'm so sorry for all the silly mistakes I did and promise that I'll keep them in mind whenever I'm contributing to any OS project.
Thanks you! ❤️

2022-04-27 13:14 UTC, mourner commented
@sumitsaurabh927 no worries at all, you don't have to apologize so much — even contributors with decades of experience can easily make mistakes in PRs, and yours were very minor. You did well!

2022-04-27 13:15 UTC, sumitsaurabh927 commented
Okay. Thank you! 😊