Additional Map Tests
Leaflet/Leaflet pull request #8206
Opened 2022-05-02 13:07 UTC by stephenspol

Unit tests missed for `Map`. Closes #8145.

- [x] `setZoom`
- [x] `setZoomAround`
- [x] `fitWorld`
- [ ] `panTo`
- [ ] `panBy`
- [ ] `flyToBounds`
- [ ] `setMinZoom`
- [ ] `setMaxZoom`
- [ ] `panInsideBounds`
- [ ] `stop`
- [ ] `locate`
- [ ] `stopLocate`
- [ ] `addHandler`
- [ ] `createPane`
- [ ] `getPane`
- [ ] `getPanes`
- [ ] `getContainer`
- [ ] `getSize`
- [ ] `getPixelBounds`
- [ ] `getPixelOrigin`
- [ ] `getPixelWorldBounds`
- [ ] `project`
- [ ] `unproject`
- [ ] `layerPointToLatLng`
- [ ] `latLngToLayerPoint`
- [ ] `distance`
- [ ] `containerPointToLayerPoint`
- [ ] `layerPointToContainerPoint`
- [ ] `containerPointToLatLng`
- [ ] `latLngToContainerPoint`
- [ ] `mouseEventToContainerPoint`
- [ ] `mouseEventToLayerPoint`
- [ ] `mouseEventToLatLng`

Some options such as `animate` and `maxZoom` are not covered as I don't know the functionality as examples are missing in the source. Also, please let me know if I miss any functionality or known bugs.

2022-05-03 13:48 UTC, stephenspol commented on spec/suites/map/MapSpec.js
> +			});
Not sure if the intended function is to move to the appropriate zoom or actual change the zoom value.

```
if (this.getZoom() < this.options.minZoom) {
	return this.setZoom(zoom);
}
```

2022-07-17 17:39 UTC, jonkoops commented
@stephenspol Thanks for the PR, it's much appreciated! Could you do me a solid and try to split this work into separate PRs for each method to reduce the cognitive load of the review?

2022-07-17 21:07 UTC, Falke-Design requested changes
@jonkoops I reviewed the tests and for me it would be ok to keep the already implmented tests  and merge this PR (if no new tests will be added). Is that ok for you too?

@stephenspol can you please fix the requested changes and all the `.skip` tests. After that I would like to merge this PR as soon as possible.

2022-07-18 02:39 UTC, stephenspol commented
Sorry for the sudden stop of progress on this PR but I have fixed the recommended changes. Please let me know if any test names or test functionalities need updated.

2022-07-18 14:26 UTC, jonkoops commented
@Falke-Design fair enough, we can certainly land this if you'd like. Let me take a look and see if this all makes sense.

2022-07-18 14:30 UTC, Falke-Design approved these changes

2022-07-18 14:30 UTC, merged

2022-07-18 14:31 UTC, Falke-Design commented
@stephenspol thank you for your contribution! If you want to implement more test, please bundle them into smaller PRs.