Closes #8145 : Tests for Map:mouseEventToLayerPoint
Leaflet/Leaflet pull request #8405
Opened 2022-08-18 12:39 UTC by kreloaded

added tests for mouseEventToLayerPoint:

- for throwing error if Map is not set
- for getting required co-ordinates when a mouseEvent occurs

2022-08-30 10:48 UTC, jonkoops approved these changes

2022-08-30 11:15 UTC, jonkoops requested changes

2022-08-30 11:15 UTC, jonkoops commented on spec/suites/map/MapSpec.js
> +			const mouseEvent = new MouseEvent('mouseenter', {
```suggestion
			var mouseEvent = new MouseEvent('mouseenter', {
```

2022-08-30 11:15 UTC, jonkoops commented on spec/suites/map/MapSpec.js
> +			const p = map.mouseEventToLayerPoint(mouseEvent);
```suggestion
			var p = map.mouseEventToLayerPoint(mouseEvent);
```

2022-09-14 05:47 UTC, kreloaded commented
Conflicts have been resolved! @jonkoops Please let me know if there's anything to add/resolve.

2023-07-07 18:02 UTC, tangerine-orange commented
@jonkoops @kreloaded is this branch ready to merge?

2025-09-30 07:26 UTC, closed without merging

2025-09-30 07:26 UTC, jonkoops commented
Closing this PR, as we no longer have a `mouseEventToLayerPoint()` method in v2. This has since been migrated to pointer events.