panBy() test
Leaflet/Leaflet pull request #8420
Opened 2022-08-29 07:00 UTC by adrianaris

#8366

2022-09-30 19:08 UTC, Falke-Design requested changes

2022-09-30 19:08 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +			}).to.throwError();
The exception is throw because `panBy` has no argument, not because `setView` call is missing. Please fix

2022-09-30 19:08 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +		it("throws if map is not set befor", function () {
```suggestion
		it("throws if view is not set before", function () {
```

2022-10-08 16:39 UTC, jonkoops commented
@adrianaris could you rebase your PR on `main`?

2022-10-08 16:40 UTC, jonkoops approved these changes

2022-10-08 17:03 UTC, Falke-Design approved these changes

2022-10-08 17:04 UTC, merged