Cover Map Locate with Unit Tests
Leaflet/Leaflet pull request #8424
Opened 2022-09-02 04:17 UTC by stephenspol

Test Cover `locate` method in `Map.js`. 

I saw there already was a `describe` for `#Geolocation`. Let me know if you would  like me to put these tests within the `describe` block. I am also not testing private methods related to Geolocation but I can if that is desired.

PR closes #8370.

2022-09-07 13:19 UTC, stephenspol commented on spec/suites/map/MapSpec.js
> +			});
Let me know if there is a better way to stub geolocation.

2022-10-01 18:29 UTC, Falke-Design requested changes
Looks very nice, only a few small changes

2022-10-01 18:29 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +				expect(data.latlng).to.eql(L.latLng(50, 50));
```suggestion
				expect(data.latlng).to.be.nearLatLng(expectedLatLngs);
```

2022-10-01 18:29 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +			expect(map.getCenter().distanceTo([50, 50])).to.be(0);
Please use `nearLatLng` and expectedLatLngs

2022-10-01 18:29 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +			var expectedBounds;
```suggestion
			var expectedBounds;
			var expectedLatLngs = [50, 50];
```

2022-10-01 18:29 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +				expect(data.latlng).to.eql(L.latLng(25, 25));
Please use nearLatLng and expectedLatLngs

2022-10-01 18:29 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +			expect(map.getCenter().distanceTo([25, 25])).to.be(0);
Please use nearLatLng and expectedLatLngs

2022-10-01 18:29 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +				expect(data.latlng).to.eql(L.latLng(50, 50));
Please use nearLatLng

2022-10-02 07:37 UTC, Falke-Design approved these changes
Great, thank you!

2022-10-02 07:37 UTC, merged