Fly to bounds tests
Leaflet/Leaflet pull request #8428
Opened 2022-09-06 18:34 UTC by Belair34

Tests to resolve issue #8367
Let me know what you think.
I made 3 different versions of the main test to demonstrate that the accuracy varies depending on the resulting zoom level.

2022-09-08 18:00 UTC, Falke-Design requested changes
Thank you for your contribution. Please check the requested changes

2022-09-08 18:00 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +				map.flyToBounds(L.latLngBounds([20, 10], [10, 20])); // arbitrary bounds
Can you please add the same test for `map.flyToBounds([[20, 10], [10, 20]]);`

2022-09-08 18:00 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +				expect(map.getCenter().distanceTo(expectedCenter)).to.be.lessThan(6600);
Please use latlng validation for the center

2022-09-08 18:00 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +			container.style.visibility = "hidden";
Is it possible to use the default style? In `createContainer` width and height are set to 400

2022-09-30 18:01 UTC, Falke-Design requested changes
@Belair34 Tests are failing

2022-10-03 12:19 UTC, Belair34 commented
> @Belair34 Tests are failing

Weird, I could have sworn they were passing back then. Should be fixed now!

2022-10-12 16:33 UTC, mourner requested changes
I'm a bit worried about the new tests being pretty slow. Do we have to run them fully animated?

```
Slowest Tests
3529ms Map #flyToBounds moves approximately to requested bounds and corresponding center (high zoom case)                            
1963ms Map #flyToBounds moves approximately to requested bounds and corresponding center (middle zoom case)                          
1578ms Map #flyToBounds moves approximately to requested bounds and corresponding center (low zoom case)                             
```

Maybe it would be enough to only test `map._getBoundsCenterZoom`? Since `flyToBounds` is only a tiny wrapper around `flyTo` which is already covered.

2022-10-13 13:27 UTC, Belair34 commented
@mourner I increased the speed of the tests similar to in flyTo, and confirmed that they are still valid.

2025-09-30 14:19 UTC, Falke-Design commented
Thank you for your contribution but this is already covered by #9112

2025-09-30 14:19 UTC, closed without merging