Add step for release assets
Leaflet/Leaflet pull request #8494
Opened 2022-09-29 12:10 UTC by IvanSanchez

Fixes #8492

2022-09-29 13:35 UTC, jonkoops requested changes

2022-09-29 13:35 UTC, jonkoops commented on RELEASE.md
> +- [ ] Create a zipfile containing all the files inside the `dist` directory, and upload it as an "asset" of the GitHub release
This ZIP archive is already [uploaded by the CI](https://github.com/Leaflet/Leaflet/blob/81b140bb2668dd6b605ffba899a7a560484d6cf2/.github/workflows/main.yml#L147) at this point, so there is no need to do this manually. It's available from the URL https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/vX.X.X/leaflet.zip

Where `X.X.X` is the version number.

2022-10-02 09:43 UTC, Falke-Design commented on RELEASE.md
> +- [ ] Create a zipfile containing all the files inside the `dist` directory, and upload it as an "asset" of the GitHub release
```suggestion
- [ ] Download zip archiv from https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/vX.X.X/leaflet.zip and upload it as an "asset" of the GitHub release
```

2022-10-04 09:39 UTC, mourner approved these changes

2022-10-04 09:39 UTC, merged