docs: :memo: Adding documentation for the support of lon in the latLng function, resolves 8509
Leaflet/Leaflet pull request #8524
Opened 2022-10-04 12:29 UTC by brianferry

### Issue

#8509 

### What I Did

Updated the reference docs and the comments in the LatLng.js file to include notes outlining the ability to use `lon` instead of `lng` when passing in an object to a function that uses the LatLng object.  References to where this functionality came from can be found in the issue and are present for compatibility with other services such as D3.js.

2022-10-04 14:19 UTC, jonkoops requested changes

2022-10-04 14:24 UTC, mourner commented on src/geo/LatLng.js
> + * map.panTo({lat: 50, lng: 30}); // Note: `lon` can be used interchangably with `lng` in objects.
I think it's clearer with an example:

```suggestion
 * map.panTo({lat: 50, lng: 30});
 * map.panTo({lat: 50, lon: 30});
```

2022-10-04 14:34 UTC, Falke-Design commented on src/geo/LatLng.js
> +// As noted previously, `lon` can be used in place of `lng` when passing in an object to this function.
I have no big opinion about this but if the users passes `{ lat: 1, lon: 3}` the LatLng object will only accessible over `latlng.lng`. So it is more a compatibility feature then `lng`

2022-10-04 20:27 UTC, brianferry commented on src/geo/LatLng.js
> +// As noted previously, `lon` can be used in place of `lng` when passing in an object to this function.
These are all fair points, while they're both valid means of setting the values in this function there's only one getter and that's the .lng value.  What do we think about outlining that like "You can also use `lon` in place of `lng` in the object form.  Both `lon` and `lng` are assigned to the `.lng` property."?

2022-10-04 20:46 UTC, Falke-Design commented on src/geo/LatLng.js
> +// As noted previously, `lon` can be used in place of `lng` when passing in an object to this function.
Sounds good to me 👍 @mourner, @jonkoops?

2022-10-04 20:47 UTC, Falke-Design requested changes

2022-10-04 20:47 UTC, Falke-Design commented on docs/reference.html
> +map.panTo({lat: 50, lng: 30}); // Note: `lon` can be used interchangably with `lng` in objects.
Please revert this file, it is generated over a script. It's enough to change the doc in `LatLng.js`

2022-10-04 20:51 UTC, jonkoops approved these changes
Changes look good. As @Falke-Design mentioned we don't need to update `docs/reference.html`, so please revert that file.

2022-10-04 20:53 UTC, jonkoops commented on src/geo/LatLng.js
> +// As noted previously, `lon` can be used in place of `lng` when passing in an object to this function.
I'm good with how the changes are now. I agree with @mourner not to be too verbose.

2022-10-04 21:29 UTC, brianferry commented
Thanks @jonkoops, I have reverted that file, thank you!

2022-10-05 05:26 UTC, Falke-Design approved these changes

2022-10-05 05:34 UTC, merged