Add dev dependency http-server for debugging ESM
Leaflet/Leaflet pull request #8848
Opened 2023-02-13 16:56 UTC by jessetane

2023-02-13 17:02 UTC, Falke-Design commented
I have nearly no experience with ESM, can you please explain why this is needed?

2023-02-13 17:04 UTC, jonkoops requested changes
@jessetane can you run `npm install` so the lockfile is also updated?

2023-02-13 17:04 UTC, jonkoops commented on package.json
> +    "debug": "http-server --port 3000 -c-1",
I think we can fall back to the default port number here.
```suggestion
    "debug": "http-server -c-1",
```

2023-02-13 17:09 UTC, jonkoops commented
> I have nearly no experience with ESM, can you please explain why this is needed?

The CORS policy for scripts loaded with `type=module` is different. So unlike regular scripts they will not load from the file-ystem directly. For example, if I open up one of the recently converted files in the debug section I get the following error:

![image](https://user-images.githubusercontent.com/695720/218524760-58f5afd3-76a1-4a3d-b50a-19e383143541.png)

2023-02-13 17:34 UTC, Falke-Design commented
> The CORS policy for scripts loaded with `type=module` is different. So unlike regular scripts they will not load from the file-ystem directly. For example, if I open up one of the recently converted files in the debug section I get the following error:

Ou ok thank you ... now i like it even less 😄

2023-02-13 17:57 UTC, jessetane commented
agree with you @Falke-Design that not being able to load modules directly from the filesystem is annoying... does anyone know why this limitation exists? i assume there is a good reason but it's not immediately obvious to me and it didn't jump out on a quick glance at the [spec](https://tc39.es/ecma262/#sec-modules). see also: https://github.com/whatwg/html/issues/8121. maybe this will change in the future?

2023-02-13 18:05 UTC, jessetane commented
more here https://github.com/whatwg/html/issues/1888

2023-02-13 18:17 UTC, jessetane commented
the arguments there are pretty esoteric, not sure i can fully grasp them without more study but i guess i still prefer being forced to use an http server than non-standard build tools

2023-02-14 21:46 UTC, jonkoops commented
It is what it is, having a HTTP server running is not the end of the world 😉

2023-02-14 21:52 UTC, jonkoops approved these changes
LGTM

2023-02-14 21:53 UTC, merged