Apply mix-blend-mode only on tile images
Leaflet/Leaflet pull request #8907
Opened 2023-04-08 17:58 UTC by Falke-Design

Fix `mix-blend-mode` issue with custom svg-tiles. The bug was introduced in #8891.

Needs to be cherry-picked into `v1`

2023-04-08 19:48 UTC, IvanSanchez requested changes

2023-04-08 19:48 UTC, IvanSanchez commented on dist/leaflet.css
> +}
Nitpicking: This closing brace should be indented, for consistency with the rest.

2023-04-08 19:50 UTC, IvanSanchez commented
Other than my nitpicking on the CSS formatting, looks good to me. I'd like @joeberkovitz to have a look and see if #8905 is fixed satisfactorily.

2023-04-08 23:02 UTC, IvanSanchez approved these changes

2023-04-09 12:44 UTC, joeberkovitz commented
I have retested this and #8905 appears to be fixed by this PR, while still addressing the original concern of gaps between tiles.

2023-04-09 13:34 UTC, merged

2023-04-11 17:04 UTC, jonkoops commented
Nice, thanks for fixing this @Falke-Design