Bugfix: Fix overriden options for fitBounds method
Leaflet/Leaflet pull request #8911
Opened 2023-04-10 12:57 UTC by AbdullahSohail-SE

Current implementation overrides provided options for fitBounds method plus noMoveStart option is also overriden to false value.

2023-04-10 13:18 UTC, veitbjarsch commented
Would be awesome if we could bring this adjustment into the next release.

2023-04-10 14:38 UTC, Falke-Design commented
We need to check if the docs needs to be updated. https://leafletjs.com/reference.html#zoom-options

2023-04-10 19:44 UTC, veitbjarsch commented
The docs describe the noMoveStart as inherit from panning. But it didn't worked before.

2023-04-11 11:52 UTC, AbdullahSohail-SE commented
@veitbjarsch seconded, cc: @Falke-Design

2023-04-13 12:37 UTC, AbdullahSohail-SE commented
@Falke-Design any updates?

2023-05-07 10:55 UTC, veitbjarsch commented
@mourner @jonkoops @IvanSanchez any chance to get this into the next release? Would love to use it.

2023-05-18 07:43 UTC, Falke-Design requested changes

2023-05-18 07:43 UTC, Falke-Design commented on src/map/Map.js
> +
```suggestion
			    ._moveStart(true, options.noMoveStart ?? false)
```

2023-05-18 07:43 UTC, Falke-Design approved these changes

2023-05-18 07:49 UTC, merged