leaflet-dataclassification plugin (dataviz category)
Leaflet/Leaflet pull request #9076
Opened 2023-08-28 19:40 UTC by balladaniel

2023-08-29 06:20 UTC, Falke-Design requested changes

2023-08-29 06:20 UTC, Falke-Design commented on docs/_plugins/dataviz/leaflet-dataclassification.md
> +Describe here your **plugin**, you can use *markdown* to format your text. Keep it short and check out the [plugin guide](https://github.com/Leaflet/Leaflet/blob/main/PLUGIN-GUIDE.md).
Please describe your plugin

2023-08-29 08:20 UTC, balladaniel commented on docs/_plugins/dataviz/leaflet-dataclassification.md
> +Describe here your **plugin**, you can use *markdown* to format your text. Keep it short and check out the [plugin guide](https://github.com/Leaflet/Leaflet/blob/main/PLUGIN-GUIDE.md).
Added plugin description, fixed.

2023-09-01 18:28 UTC, Falke-Design approved these changes

2023-09-01 18:33 UTC, merged