Updated Twitter Logo and Name
Leaflet/Leaflet pull request #9102
Opened 2023-09-24 20:56 UTC by aialok

2023-09-24 23:04 UTC, jonkoops requested changes
I think we'll also have to update the `alt` attibute so it references X rather than Twitter. There are also various places where we still refer to 'Twitter' and 'tweeting', which should also be updated.

2023-09-24 23:04 UTC, jonkoops commented on docs/docs/images/twitter-round.svg
Did you run this file through [SVGO](https://github.com/svg/svgo)? If not, could you do so?

2023-09-25 06:23 UTC, aialok commented
> I think we'll also have to update the `alt` attibute so it references X rather than Twitter. There are also various places where we still refer to 'Twitter' and 'tweeting', which should also be updated.

2023-09-25 06:24 UTC, aialok commented on docs/docs/images/twitter-round.svg
What should be the alternative of tweeting ?

2023-09-25 06:28 UTC, aialok commented on docs/docs/images/twitter-round.svg
Optimize SVG file using SVGO.

2023-09-25 08:08 UTC, aialok commented on docs/docs/images/twitter-round.svg
Hello Sir I have updated the code....do check it out if any further improvement needed...do tell me.
Thank you !
Happy Coding !

2023-09-25 09:07 UTC, jonkoops commented on docs/docs/images/twitter-round.svg
That's a good question. What does Elon say?

2023-09-25 09:10 UTC, jonkoops commented on docs/index.html
> +X to <a href="https://twitter.com/LeafletJS">@LeafletJS</a>
Not quit sure what to use instead of 'tweeting', X-ing sounds kinda vulgar :laughing:

2023-09-25 09:10 UTC, jonkoops commented on docs/docs/images/twitter-round.svg
Thanks! Consider this resolved.

2023-09-25 09:10 UTC, jonkoops commented on docs/docs/images/twitter-round.svg
Let's discuss this under https://github.com/Leaflet/Leaflet/pull/9102#discussion_r1335606739. Considering this resolved.

2023-09-25 09:43 UTC, aialok commented on docs/docs/images/twitter-round.svg
Thank you sir....This is my first open Source contribution.

2023-09-25 09:46 UTC, aialok commented on docs/index.html
> +X to <a href="https://twitter.com/LeafletJS">@LeafletJS</a>
we can use 'xeets' in place of 'tweets'....haha

2023-09-27 06:47 UTC, WebSnke commented on docs/index.html
> +X to <a href="https://twitter.com/LeafletJS">@LeafletJS</a>
I think saying to X would be the best option.

We could also use "X's" in playce of "tweets".

2023-09-27 12:24 UTC, aialok commented on docs/index.html
> +X to <a href="https://twitter.com/LeafletJS">@LeafletJS</a>
Will this issue got resolved ?
I am new to open source...when will this going to merge ?

2023-10-01 17:52 UTC, aialok commented
Sir Can You Please merge this pull request.....If there is any issue please tell me to fix.
Thank You !

2023-10-01 20:43 UTC, Falke-Design approved these changes

2023-10-01 20:44 UTC, merged

2023-10-01 20:44 UTC, Falke-Design commented
Hi @aialok thank you for your contribution, nice work. And welcome in the OpenSource world 😉 

For the future: if you are creating a PR, please add a [linking keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) like "fixes" or "closes" (`Fixes: #9096`), to reference the issue. The issue will then automatically closed when this PR is merged.

@WebSnke thank you for helping.

2023-10-01 21:44 UTC, aialok commented
Thank you so much sir ! 
Looking forward to contribute more in the open source world : )

2024-05-02 09:00 UTC, aialok commented
@jonkoops @Falke-Design  thank you so much.
This PR is reason for me to comes to open source world : )
This journey comes far that now I am selected for GSoC as a contributor in postman this year : )

Thank you : )