flyToBounds test addes
Leaflet/Leaflet pull request #9112
Opened 2023-10-02 03:04 UTC by shreya024

Implemented tests for flyToBounds method of Map(#8145)

2023-10-04 20:43 UTC, Falke-Design requested changes
Please revert all the code changes from the auto formatter. 

After a quick look, the new tests are looking pretty good besides the timeout

2023-10-04 20:43 UTC, Falke-Design commented on spec/suites/map/MapSpec.js
> +			this.timeout(10000);
```suggestion
```

The tests should not need the 10 seconds. Please try to disable animation: `map.setView([0, 0], 0, {animate: false});`, `map.flyToBounds(bounds, {animate: false})`

2023-10-24 15:30 UTC, shreya024 commented
@Falke-Design Kindly review again

2023-11-12 17:36 UTC, jonkoops approved these changes

2023-11-12 17:37 UTC, jonkoops commented
@Falke-Design shall we merge this one in? Looks like a solid addition to the test suite.

2023-11-12 20:22 UTC, Falke-Design approved these changes

2023-11-12 20:22 UTC, merged

2023-11-12 23:11 UTC, jonkoops commented
Thanks for your contribution @shreya024, it's much appreciated!