Add scroll up button to website
Leaflet/Leaflet pull request #9186
Opened 2023-12-03 21:21 UTC by simondriesen

Closes #9108

Since the other pull request has been stuck for some time I decided to give it a go as well.

2024-07-02 18:02 UTC, Falke-Design requested changes
@simondriesen really nice, thank you! What do you think about showing the box-shadow always?

2024-07-02 18:02 UTC, Falke-Design commented on docs/docs/css/main.css
> +  background-color: #eee;
```suggestion
	background-color: #eee;
```

2024-07-03 12:35 UTC, simondriesen commented on docs/docs/css/main.css
> +		box-shadow: rgba(14, 15, 15, 0.3) 0px 2px 10px 0px;
It was a bit of an afterthought to make it pop out more on mobile but I guess it doesn't hurt to have it on desktop too.

2024-07-03 12:48 UTC, simondriesen commented
![image](https://github.com/Leaflet/Leaflet/assets/9056487/93244dd0-9646-4fd9-a6c0-c2f15ab9b273)

I also gave the button a higher z-index because it the "overview" page it was hiding behind the map on mobile.

2024-07-05 13:45 UTC, Falke-Design approved these changes

2024-07-05 18:24 UTC, merged

2024-07-05 18:24 UTC, Falke-Design commented
@simondriesen thank you!