Solution to issue 9067 - Inverting x axis of L.CRS.Simple causes L.Circle to have no radius
Leaflet/Leaflet pull request #9414
Opened 2024-07-26 22:30 UTC by bakp22

solves #9067

## Solution to issue 9067 - Inverting x axis of L.CRS.Simple causes L.Circle to have no radius
**Identified cause**: In Circle.js, the radius was being returned as negative once it was altered through different modifications towards itself presumably because of the transformation method requirements and the project method.

**Solution**: Math.abs() surrounded the calculation of the returned radius making it positive instead of negative. “npm run test” was performed to see if this change made additional errors. All tests were successfull.

2024-07-27 13:41 UTC, IvanSanchez approved these changes

2024-07-27 16:13 UTC, Falke-Design requested changes
Can you please add a new test for this special case

2024-07-30 22:16 UTC, bakp22 commented
We will work on this right now. Should we use an existing test suite or make one for this specific case?

2024-08-13 22:51 UTC, bakp22 commented
We have been struggling to figure out how to get the circle to fully render inside our tests. The way we are creating a circle isn't calling the _project function when it is being added to a map in our test file. Could you please provide some assistance? 
Also, this case passes however continues to pass after making changes to the source code to intentionally cause a failure.

Current Code:
```js
		function createCircleWithTransformation(crs){
			container = container = createContainer();
			map = new Map(container, {crs});
			console.log(crs.distance);
			return new Circle([50,30], {radius: 10, crs: crs}).addTo(map)
		}

		

		// TEST FOR DEFAULT TRANSFORMATION
		it('returns a positive radius after default transformation', () => {
			let crs = L.Util.extend(L.CRS.Simple, {
				transformation: new L.Transformation(1, 0, 1, 0),
			});
			const circle = createCircleWithTransformation(crs)
			expect(circle.getRadius()).to.be.greaterThan(0);
			expect(circle.getRadius()).to.equal(10);
			
		});

2025-03-01 08:33 UTC, Falke-Design approved these changes

2025-03-01 08:34 UTC, merged

2025-03-01 08:34 UTC, Falke-Design commented
Thank you for your contirbution