Fix Leaflet attribution link
Leaflet/Leaflet pull request #9471
Opened 2024-09-12 17:17 UTC by florian-h05

The Leaflet attribution link was not marked as external, which led to the leaflet link getting added to the current path.

This adds the required class and target attributes to the anchor.

2024-09-28 10:29 UTC, florian-h05 commented
Hi @Falke-Design and sorry for pinging you, it would be great if you could have a look at this one liner.
Best regards!

2024-09-28 11:12 UTC, Falke-Design requested changes

2024-09-28 11:12 UTC, Falke-Design commented on src/control/Control.Attribution.js
> +		prefix: `<a class="external" target="_blank" href="https://leafletjs.com" title="A JavaScript library for interactive maps">${ukrainianFlag}Leaflet</a>`
```suggestion
		prefix: `<a target="_blank" href="https://leafletjs.com" title="A JavaScript library for interactive maps">${ukrainianFlag}Leaflet</a>`
```

The class `external` is not needed

2024-09-28 11:34 UTC, florian-h05 commented
@Falke-Design Changed ✅

2024-10-23 06:04 UTC, florian-h05 commented
Any reason CI test is failing with my change?

2025-03-01 08:13 UTC, Falke-Design approved these changes

2025-03-01 08:13 UTC, merged