Create leaflet-topo-scale.md
Leaflet/Leaflet pull request #9532
Opened 2024-11-20 09:43 UTC by KomelT

2025-02-16 11:07 UTC, Falke-Design requested changes
Please add a image to your repository and add a demo page. You can host a demo directly over Github-Pages for free

2025-02-16 12:14 UTC, KomelT commented
@Falke-Design Thank you for recomendation. It is done.

2025-02-16 16:36 UTC, Falke-Design requested changes
On your demo site no scale is displayed for me:
![grafik](https://github.com/user-attachments/assets/fb8b9024-4b5f-412f-a58f-9351ceeeebc3)

2025-02-16 16:36 UTC, Falke-Design commented on docs/_plugins/measurement/leaflet-topo-scale.md
> +demo:
Please add your demo URL here too.

2025-02-16 16:53 UTC, KomelT commented
I don't understand why. I asked some of my friends to test and it has worked... Can you try CTRL + F5.

2025-02-16 17:05 UTC, Falke-Design commented
In Chrome it is working fine but not in Firefox (Windows).

When I hover over the canvas it shows that something is drawn but not displayed.
![grafik](https://github.com/user-attachments/assets/8223ad74-601e-4b5d-9740-66a38eb25d41)

2025-02-17 08:48 UTC, KomelT commented
I'm sorry, but I cannot reproduce the problem. I tried Chrome and Firefox on Windows and Linux. It's not just me; other people cannot, either.

2025-02-18 22:00 UTC, merged